/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;

public class App {

    public static void main(String[] args) throws IOException {

        ArrayList<Quote> quotes = jsonParser();
        int random = new Random().nextInt(quotes.size());
        System.out.println(quotes.get(random));


    }

    public static ArrayList<Quote> jsonParser() throws IOException {
        BufferedReader reader = new BufferedReader(new FileReader("app/src/main/resources/recentquotes.json"));

        GsonBuilder builder = new GsonBuilder();
        Gson gson = builder.create();

        return gson.fromJson(reader, new TypeToken<ArrayList<Quote>>() {}.getType());

    }

}
