/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class App {

    public static void main(String[] args) throws IOException {

        ArrayList<Quote> quotes = jsonParser();
        int random = new Random().nextInt(quotes.size());
        System.out.println(quotes.get(random));
        random = new Random().nextInt(quotes.size());
        System.out.println(quotes.get(random));


    }

    private static ArrayList<Quote> jsonParser() throws IOException {
        BufferedReader reader = new BufferedReader(new FileReader("app/src/main/resources/recentquotes.json"));

        GsonBuilder builder = new GsonBuilder();
        Gson gson = builder.create();

        return gson.fromJson(reader, new TypeToken<ArrayList<Quote>>() {}.getType());

    }

}
